namespace ASPCourceEmpty.Models
{
    public static class DBInitializer
    {
        public static void Seed(PostcardDBContext context)
        {
            if (!context.Categories.Any())
            {
                context.Categories.AddRange(Categories.Select(c => c.Value));
            }

            if (!context.Postcards.Any())
            {
                context.AddRange
                (
                    new Postcard { Name = "Caramel Popcorn Cheese Cake", Price = 22.95M, ShortDescription = "The ultimate cheese cake", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Architecture Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/caramelpopcorncheesecake.jpg", InStock = true, IsPostcardOfTheWeek = true, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/caramelpopcorncheesecakesmall.jpg", },
                    new Postcard { Name = "Chocolate Cheese Cake", Price = 19.95M, ShortDescription = "The chocolate lover's dream", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Architecture Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/chocolatecheesecake.jpg", InStock = true, IsPostcardOfTheWeek = true, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/chocolatecheesecakesmall.jpg", },
                    new Postcard { Name = "Pistache Cheese Cake", Price = 21.95M, ShortDescription = "We're going nuts over this one", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Architecture Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/pistachecheesecake.jpg", InStock = true, IsPostcardOfTheWeek = true, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/pistachecheesecakesmall.jpg", },
                    new Postcard { Name = "Pecan Postcard", Price = 21.95M, ShortDescription = "More pecan than you can handle!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/fruitPostcards/pecanPostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/fruitPostcards/pecanPostcardsmall.jpg", },
                    new Postcard { Name = "Birthday Postcard", Price = 29.95M, ShortDescription = "A Happy Birthday with this Postcard!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/seasonal/birthdayPostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/seasonal/birthdayPostcardsmall.jpg", },
                    new Postcard { Name = "Apple Postcard", Price = 12.95M, ShortDescription = "Our famous apple Postcards!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applePostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applePostcardsmall.jpg", },
                    new Postcard { Name = "Blueberry Cheese Cake", Price = 18.95M, ShortDescription = "You'll love it!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Architecture Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/blueberrycheesecake.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/blueberrycheesecakesmall.jpg", },
                    new Postcard { Name = "Cheese Cake", Price = 18.95M, ShortDescription = "Plain cheese cake. Plain pleasure.", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Architecture Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/cheesecake.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysPostcardshop/cheesecakes/cheesecakesmall.jpg", },
                    new Postcard { Name = "Cherry Postcard", Price = 15.95M, ShortDescription = "A summer classic!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherryPostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cherryPostcardsmall.jpg", },
                    new Postcard { Name = "Christmas Apple Postcard", Price = 13.95M, ShortDescription = "Happy holidays with this Postcard!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplePostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplePostcardsmall.jpg", },
                    new Postcard { Name = "Cranberry Postcard", Price = 17.95M, ShortDescription = "A Christmas favorite", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberryPostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberryPostcardsmall.jpg", },
                    new Postcard { Name = "Peach Postcard", Price = 15.95M, ShortDescription = "Sweet as peach", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachPostcard.jpg", InStock = false, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/peachPostcardsmall.jpg", },
                    new Postcard { Name = "Pumpkin Postcard", Price = 12.95M, ShortDescription = "Our Halloween favorite", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Seasonal Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinPostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinPostcardsmall.jpg", },
                    new Postcard { Name = "Rhubarb Postcard", Price = 15.95M, ShortDescription = "My God, so sweet!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbPostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbPostcardsmall.jpg", },
                    new Postcard { Name = "Strawberry Postcard", Price = 15.95M, ShortDescription = "Our delicious strawberry Postcard!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Fruit Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberryPostcard.jpg", InStock = true, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberryPostcardsmall.jpg", },
                    new Postcard { Name = "Strawberry Cheese Cake", Price = 18.95M, ShortDescription = "You'll love it!", LongDescription = "Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake Postcard chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon Postcard muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart Postcard cake danish lemon drops. Brownie cupcake dragée gummies.", Category = Categories["Architecture Postcards"], ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecake.jpg", InStock = false, IsPostcardOfTheWeek = false, ImageThumbnailUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg", }
                );
            }

            context.SaveChanges();
        }

        private static Dictionary<string, Category>? categories;

        public static Dictionary<string, Category> Categories
        {
            get
            {
                if (categories == null)
                {
                    var genresList = new Category[]
                    {
                        new Category { CategoryName = "Fruit Postcards" },
                        new Category { CategoryName = "Architecture Postcards" },
                        new Category { CategoryName = "Seasonal Postcards" }
                    };

                    categories = new Dictionary<string, Category>();

                    foreach (Category genre in genresList)
                    {
                        categories.Add(genre.CategoryName, genre);
                    }
                }

                return categories;
            }
        }
    }
}
